version: '3.8'
services:
  ros2:
    tty: true
    image: skyrexdev/ros2-humble-nvidia:latest
    container_name: ros2
    build: ./
    environment:
      - DISPLAY
      - GAZEBO_AUDIO_DISABLED=1
      - TURTLEBOT3_MODEL=burger
    volumes:
      - $PWD/:/mnt/scripts
      - /tmp/.X11-unix:/tmp/.X11-unix
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
